
-----------Total revenue
Purpose
Measure overall revenue generated by the business to assess financial health.
    
Query:    
select sum(revenue) as total_revenue
from business_kpi_data;

Insight
The business has generated a strong cumulative revenue, indicating steady monetization across customers and plans.
Executive takeaway:
Revenue base is stable and scalable.
    
----------total costumers
Purpose
Understand the total size of the customer base.

select count(Distinct customer_id) as total_revenue
from business_kpi_data;

Insight
The company has acquired a healthy number of customers, showing consistent growth over time.
Executive takeaway:
Customer acquisition is active and ongoing.

--------------Active Costumers
Purpose
Identify how many customers are currently active and using the product.
    
select count(Distinct customer_id) as active_costumers
from business_kpi_data
where is_active = 1;

Insight
A majority of customers are active, suggesting good product adoption and engagement.
Executive takeaway:
Most users are retained, but retention optimization can further improve health.
    
------------churned costumers
Purpose
Identify customers who are no longer active to understand churn volume.
    
select count(Distinct customer_id) as active_costumers
from business_kpi_data
where is_active = 0;

Insight
A noticeable portion of customers have churned, highlighting potential retention gaps.
Executive takeaway:
Churn is present and should be monitored proactively.
    
-------- churn rate
Purpose
Quantify customer loss as a percentage of total customers.

select round(count
(case when is_active=0 then customer_id end)*100.0/
count (Distinct customer_id)
,2
) as churned_rate_percent
from business_kpi_data;

Insight
The churn rate is moderate, indicating that while growth exists, retention strategies need strengthening.
Executive takeaway:
Reducing churn even slightly could significantly improve long-term revenue.
    
----------- average revenue per user
Purpose
Measure revenue efficiency per customer.

select 
round(sum(revenue)*1.0/count(distinct customer_id),2) as average_revenue_per_user
from business_kpi_data;

Insight
Premium users significantly increase ARPU, while basic plans contribute lower revenue.
Executive takeaway:
Upselling customers to higher plans can materially boost revenue.
    
---------- Revenue Trend over time
Purpose
Track revenue growth or decline across months.
    
select date,sum(revenue) as montly_revenue
from business_kpi_data
group by date
order by date;

Insight
Revenue shows an upward trend over time, indicating positive business momentum.
Executive takeaway:
Business growth is sustainable, with increasing monthly revenue.
    
----------- revenue by plan
Purpose
Understand which subscription plans drive the most revenue.

select plan,sum(revenue) as total_revenue
from business_kpi_data
group by plan
order by total_revenue desc;

Insight
Premium plans contribute the highest share of revenue despite fewer customers.
Executive takeaway:
Premium plans are the core revenue drivers.
    
-------------revenue by region
Purpose
Identify high-performing geographic regions.
    
select region,sum(revenue) as total_revenue
from business_kpi_data
group by region
order by total_revenue desc;

Insight
India and the US generate the majority of revenue, while the UK shows moderate contribution.
Executive takeaway:
Growth investments should prioritize high-revenue regions.

------------ high risk segment(churn by plan)
Purpose
Identify which subscription plans experience the highest churn.

SELECT plan,
COUNT(CASE WHEN is_active = 0 THEN customer_id END) AS churned_customers,
COUNT(customer_id) AS total_customers,
ROUND(
  COUNT(CASE WHEN is_active = 0 THEN customer_id END) * 100.0 
 / COUNT(customer_id),2 ) AS churn_rate_percent
FROM business_kpi_data
GROUP BY plan

Insight
Basic plans show the highest churn rate, indicating lower long-term value and engagement.
Executive takeaway:
Basic plan users require better onboarding or incentives to retain.
ORDER BY churn_rate_percent DESC;
